; Auto-generated. Do not edit!


(cl:in-package agile_v_core-msg)


;//! \htmlinclude kinematics.msg.html

(cl:defclass <kinematics> (roslisp-msg-protocol:ros-message)
  ((CM_Velocity
    :reader CM_Velocity
    :initarg :CM_Velocity
    :type (cl:vector cl:float)
   :initform (cl:make-array 2 :element-type 'cl:float :initial-element 0.0))
   (CM_Acceleration
    :reader CM_Acceleration
    :initarg :CM_Acceleration
    :type (cl:vector cl:float)
   :initform (cl:make-array 2 :element-type 'cl:float :initial-element 0.0))
   (Vehicle_Heading
    :reader Vehicle_Heading
    :initarg :Vehicle_Heading
    :type cl:float
    :initform 0.0)
   (CM_AngularVel
    :reader CM_AngularVel
    :initarg :CM_AngularVel
    :type cl:float
    :initform 0.0)
   (CM_AngularAcc
    :reader CM_AngularAcc
    :initarg :CM_AngularAcc
    :type cl:float
    :initform 0.0)
   (Wheel_LinearVel
    :reader Wheel_LinearVel
    :initarg :Wheel_LinearVel
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Wheel_SteerAngl
    :reader Wheel_SteerAngl
    :initarg :Wheel_SteerAngl
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Time_Stamp
    :reader Time_Stamp
    :initarg :Time_Stamp
    :type cl:real
    :initform 0))
)

(cl:defclass kinematics (<kinematics>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <kinematics>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'kinematics)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name agile_v_core-msg:<kinematics> is deprecated: use agile_v_core-msg:kinematics instead.")))

(cl:ensure-generic-function 'CM_Velocity-val :lambda-list '(m))
(cl:defmethod CM_Velocity-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:CM_Velocity-val is deprecated.  Use agile_v_core-msg:CM_Velocity instead.")
  (CM_Velocity m))

(cl:ensure-generic-function 'CM_Acceleration-val :lambda-list '(m))
(cl:defmethod CM_Acceleration-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:CM_Acceleration-val is deprecated.  Use agile_v_core-msg:CM_Acceleration instead.")
  (CM_Acceleration m))

(cl:ensure-generic-function 'Vehicle_Heading-val :lambda-list '(m))
(cl:defmethod Vehicle_Heading-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:Vehicle_Heading-val is deprecated.  Use agile_v_core-msg:Vehicle_Heading instead.")
  (Vehicle_Heading m))

(cl:ensure-generic-function 'CM_AngularVel-val :lambda-list '(m))
(cl:defmethod CM_AngularVel-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:CM_AngularVel-val is deprecated.  Use agile_v_core-msg:CM_AngularVel instead.")
  (CM_AngularVel m))

(cl:ensure-generic-function 'CM_AngularAcc-val :lambda-list '(m))
(cl:defmethod CM_AngularAcc-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:CM_AngularAcc-val is deprecated.  Use agile_v_core-msg:CM_AngularAcc instead.")
  (CM_AngularAcc m))

(cl:ensure-generic-function 'Wheel_LinearVel-val :lambda-list '(m))
(cl:defmethod Wheel_LinearVel-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:Wheel_LinearVel-val is deprecated.  Use agile_v_core-msg:Wheel_LinearVel instead.")
  (Wheel_LinearVel m))

(cl:ensure-generic-function 'Wheel_SteerAngl-val :lambda-list '(m))
(cl:defmethod Wheel_SteerAngl-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:Wheel_SteerAngl-val is deprecated.  Use agile_v_core-msg:Wheel_SteerAngl instead.")
  (Wheel_SteerAngl m))

(cl:ensure-generic-function 'Time_Stamp-val :lambda-list '(m))
(cl:defmethod Time_Stamp-val ((m <kinematics>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader agile_v_core-msg:Time_Stamp-val is deprecated.  Use agile_v_core-msg:Time_Stamp instead.")
  (Time_Stamp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <kinematics>) ostream)
  "Serializes a message object of type '<kinematics>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'CM_Velocity))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'CM_Acceleration))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'Vehicle_Heading))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'CM_AngularVel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'CM_AngularAcc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Wheel_LinearVel))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Wheel_SteerAngl))
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'Time_Stamp)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'Time_Stamp) (cl:floor (cl:slot-value msg 'Time_Stamp)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <kinematics>) istream)
  "Deserializes a message object of type '<kinematics>"
  (cl:setf (cl:slot-value msg 'CM_Velocity) (cl:make-array 2))
  (cl:let ((vals (cl:slot-value msg 'CM_Velocity)))
    (cl:dotimes (i 2)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'CM_Acceleration) (cl:make-array 2))
  (cl:let ((vals (cl:slot-value msg 'CM_Acceleration)))
    (cl:dotimes (i 2)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'Vehicle_Heading) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'CM_AngularVel) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'CM_AngularAcc) (roslisp-utils:decode-double-float-bits bits)))
  (cl:setf (cl:slot-value msg 'Wheel_LinearVel) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Wheel_LinearVel)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Wheel_SteerAngl) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Wheel_SteerAngl)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'Time_Stamp) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<kinematics>)))
  "Returns string type for a message object of type '<kinematics>"
  "agile_v_core/kinematics")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'kinematics)))
  "Returns string type for a message object of type 'kinematics"
  "agile_v_core/kinematics")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<kinematics>)))
  "Returns md5sum for a message object of type '<kinematics>"
  "106ad333403d5f1ecfca19cf013ec05f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'kinematics)))
  "Returns md5sum for a message object of type 'kinematics"
  "106ad333403d5f1ecfca19cf013ec05f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<kinematics>)))
  "Returns full string definition for message of type '<kinematics>"
  (cl:format cl:nil "# Vehicle Center Kinematics on Vehicle Coordinates, MKS Units Mandatory.~%float64[2]   CM_Velocity~%float64[2]   CM_Acceleration~%float64     Vehicle_Heading~%float64     CM_AngularVel~%float64     CM_AngularAcc~%~%# Wheel Kinematics~%float64[4]   Wheel_LinearVel~%float64[4]   Wheel_SteerAngl~%~%# Time Stamp~%time        Time_Stamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'kinematics)))
  "Returns full string definition for message of type 'kinematics"
  (cl:format cl:nil "# Vehicle Center Kinematics on Vehicle Coordinates, MKS Units Mandatory.~%float64[2]   CM_Velocity~%float64[2]   CM_Acceleration~%float64     Vehicle_Heading~%float64     CM_AngularVel~%float64     CM_AngularAcc~%~%# Wheel Kinematics~%float64[4]   Wheel_LinearVel~%float64[4]   Wheel_SteerAngl~%~%# Time Stamp~%time        Time_Stamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <kinematics>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'CM_Velocity) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'CM_Acceleration) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     8
     8
     8
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Wheel_LinearVel) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Wheel_SteerAngl) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <kinematics>))
  "Converts a ROS message object to a list"
  (cl:list 'kinematics
    (cl:cons ':CM_Velocity (CM_Velocity msg))
    (cl:cons ':CM_Acceleration (CM_Acceleration msg))
    (cl:cons ':Vehicle_Heading (Vehicle_Heading msg))
    (cl:cons ':CM_AngularVel (CM_AngularVel msg))
    (cl:cons ':CM_AngularAcc (CM_AngularAcc msg))
    (cl:cons ':Wheel_LinearVel (Wheel_LinearVel msg))
    (cl:cons ':Wheel_SteerAngl (Wheel_SteerAngl msg))
    (cl:cons ':Time_Stamp (Time_Stamp msg))
))
